export const COMMIT_ISSUES = 'COMMIT_ISSUES';
export const UPDATE_ISSUE_ORDER = 'UPDATE_ISSUE_ORDER';

export const FETCH_ISSUES = 'FETCH_ISSUES';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
