export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';

export const COMMIT_REPOS = 'COMMIT_REPOS';
